CREATE TABLE IF NOT EXISTS T_TRADE (
    T_UID BIGINT PRIMARY KEY,
    T_TYPE VARCHAR(10) NOT NULL,
    T_U_UID BIGINT NOT NULL,
    T_U_NAME VARCHAR(255) NOT NULL,
    T_SYMBOL VARCHAR(20) NOT NULL,
    T_SHARES  INTEGER NOT NULL CHECK (T_SHARES > 0),
    T_PRICE NUMERIC(19,4) NOT NULL CHECK (T_PRICE > 0),
    T_CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
                                );

CREATE INDEX IF NOT EXISTS idx_trades_user_id_id ON T_TRADE (T_U_UID, T_UID);
CREATE INDEX IF NOT EXISTS idx_trades_symbol_type_timestamp_id ON T_TRADE (T_SYMBOL, T_TYPE, T_CREATED_AT, T_UID);
CREATE INDEX IF NOT EXISTS idx_trades_symbol_timestamp ON T_TRADE (T_SYMBOL, T_CREATED_AT);
